server:
  port: 8091
mybatis:
  mapper-locations: classpath:mapping/*.xml
spring:
  datasource:
    name: songs
#    url: jdbc:mysql://47.93.129.250:3306/test?characterEncoding=utf-8&useSSL=false
    url: jdbc:p6spy:mysql://127.0.0.1:3306/imageslabel?characterEncoding=utf-8&useSSL=false
    username: root
    password: kaikai
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  application:
    name: VIEW-SERVICE
#  rabbitmq:
#    username: guest
#    host: 47.93.129.250
#    password: guest


logging:
  level:
    root: warn
    com.fehead.testproject.dao: trace
  pattern:
    console: '%p%m%n'


#redis:
#  database: 0           # Redis服务器数据库
#  host: 127.0.0.1    # Redis服务器地址
#  port: 6379            # Redis服务器连接端口
#  password:      # Redis服务器连接密码（默认为空）
#  timeout: 6000ms       # 连接超时时间（毫秒）
#  jedis:
#    pool:
#      max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
#      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-idle: 10      # 连接池中的最大空闲连接
#      min-idle: 0       # 连接池中的最小空闲连接
##eureka:
#  client:
#    service-url:
##      defaultZone: http://10.111.229.84:8761/eureka
#      defaultZone: http://192.168.0.101:8761//eureka
#
#ribbon:
#  ReadTimeout: 6000000
#  ConnectTimeout: 6000000
#feign:
#  client:
#    config:
#      defualt:
#        connectTimeout: 20000
#        readTimeout: 20000
